services:
  backend:
    build:
      context: backend
      target: dev-envs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MARIADB_ROOT_PASSWORD=need-to-replace
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MARIADB_ROOT_PASSWORD=need-to-replace
    expose:
      - 3306

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  db-data:
