services:
  backend:
    build:
      context: backend
      target: builder
    environment:
      - MYSQL_DATABASE=example
      - MARIADB_ROOT_PASSWORD=need-to-replace
    expose:
      - 8000

  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MARIADB_ROOT_PASSWORD=need-to-replace
    expose:
      - 3306

  proxy:
    build:
      context: proxy
    ports:
      - 80:80

volumes:
  db-data:

