services:
  backend:
    build:
      context: backend
      target: builder
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=need-to-replace
    expose:
      - 8000

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=need-to-replace
    expose:
      - 5432

  proxy:
    build:
      context: proxy
    ports:
      - 80:80

volumes:
  db-data:
